# List of JSON configuration files
application_files:
  - './applications/peg_solitaire/peg_solitaire_1.json'
  - './applications/peg_solitaire/peg_solitaire_2.json'
  - './applications/peg_solitaire/peg_solitaire_3.json'
  - './applications/peg_solitaire/tab_peg_solitaire_1.json'
  - './applications/peg_solitaire/tab_peg_solitaire_2.json'
  - './applications/peg_solitaire/tab_peg_solitaire_3.json'
  - './applications/peg_solitaire/tab_peg_solitaire_4.json'
  - './applications/peg_solitaire/peg_solitaire_codecanyon_feature.json'
  - './applications/peg_solitaire/peg_solitaire_feature_image.json'
  - './applications/peg_solitaire/peg_solitaire_pc_icon.json'
  - './applications/peg_solitaire/peg_solitaire_feature_pc.json'
  
  
  

#  python3 -m venv venv
#  source ./venv/bin/activate